trydjango/mysite/blog/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = "blog"
urlpatterns = [
    path('', ArticleListView.as_view(), name="article_list"),
    path('create/', ArticleCreateView.as_view(), name="article_create"),
    path('<int:id>/', ArticleDetailView.as_view(), name="article_detail"),
    path('<int:id>/edit/', ArticleUpdateView.as_view(), name="article_edit"),
    path('<int:id>/delete/', ArticleDeleteView.as_view(), name="article_delete")
]

trydjango/mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from pages.views import PagesView, home_view
from products.views import cart_view, cart_buy_view, update_product_cart

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('blog/', include('blog.urls')),
    path('', home_view, name='home'),
    path('contact/', PagesView.as_view(template_name='contact.html'), name='contact'),
    path('social/', PagesView.as_view(template_name='social.html'), name='social'),
    path('about/', PagesView.as_view(template_name='about.html'), name='about'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', PagesView.as_view(template_name='user/profile.html'), name='profile'),
    path('cart/', cart_view, name='cart'),
    path('cart/buy', cart_buy_view, name='cart_buy'),
    path('cart/update', update_product_cart, name='cart_update')


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trydjango/mysite/products/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class ImageModel(models.Model):
    image = models.ImageField(null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.description


class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(null=True)
    price = models.DecimalField(max_digits=1000, decimal_places=2)
    summary = models.TextField(blank=False, null=False)
    featured = models.BooleanField(default=False)
    total_in_stock = models.PositiveIntegerField(default=0)
    count_sells = models.PositiveIntegerField(default=0)
    count_views = models.PositiveIntegerField(default=0)
    gallery = models.ManyToManyField(ImageModel, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("products:product_detail", kwargs={"id": self.id})

    def get_edit_url(self):
        return reverse("products:product_edit", kwargs={"id": self.id})

    def sell(self, amount):
        self.total_in_stock -= amount
        self.count_sells += amount

    def price_integer(self):
        return self.price // 1

    def price_coin(self):
        price = (self.price % 1) * 100
        return price // 1



class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(default=0)
    def total_price(self):
        total = self.amount * self.product.price
        return total

trydjango/mysite/templates/about.html
{% extends 'base.html' %}



{% block content %}
    <h1>About Page</h1>

    <p>This is a template</p>

<p>
    {{ my_text }}, {{ my_number }}
</p>


<ul>
    <li>Item 1</li>
    <li>Item 2</li>
</ul>

<ul>
    {% for my_sub_item in my_list %}
    {% if my_sub_item == 456 %}
        <li>{{ forloop.counter }} - {{ my_sub_item|add:22 }}</li>
    {% elif my_sub_item == 'abc' %}
        <li>This is not the network</li>
    {% else %}
        <li>{{ forloop.counter }} - {{ my_sub_item }}</li>
    {% endif %}
{% endfor %}
</ul>


{% endblock content %}

trydjango/mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>First e-Commerce by J.Merlin</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<!--    <link rel="stylesheet" href="{% static 'products/estilo.css' %}" >-->

</head>
<body id="body" class="bg-light">
    {% include 'navbar.html' %}

    {% block content %}
    replace me
    {% endblock %}


    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

trydjango/mysite/templates/cart.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    {% include 'flash_messages.html' %}
    <h1>Cart</h1>
    {% for cart_item in cart_list %}
    <div>
        {{ cart_item.product.title }}
        <div>R$<span> {{ cart_item.product.price_integer }},</span><small>{{ cart_item.product.price_coin }} </small></div>
        <form action="/cart/update" method="post">
            {% csrf_token %}
            <button class="btn btn-primary" type="submit">-</button>
            <input type="hidden" readonly="readonly" value="{{ cart_item.amount|add:-1 }}" name="amount">
            <input type="hidden" value="{{ cart_item.product.id }}" name="product_id">
        </form>
        <input type="text" readonly="readonly" value="{{ cart_item.amount }}" name="amount">
         <form action="/cart/update" method="post">
            {% csrf_token %}
            <button class="btn btn-primary" type="submit">+</button>
            <input type="hidden" readonly="readonly" value="{{ cart_item.amount|add:1 }}" name="amount">
            <input type="hidden" value="{{ cart_item.product.id }}" name="product_id">
        </form>
        <div> {{ cart_item.total_price }} </div>
    </div>
    {% endfor %}
    <form action="/cart/buy" method="post">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit">Buy</button>

    </form>

</div>

{% endblock %}

trydjango/mysite/templates/contact.html
{% extends 'base.html' %}


{% block content %}
    <h1>Contact</h1>

    <p>This is a template</p>
{% endblock %}

trydjango/mysite/templates/flash_messages.html
{% if messages %}
<ul class="messages list-unstyled">
    {% for message in messages %}
    <li {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
        <span>{{ message }}</span>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </li>
    {% endfor %}
</ul>
{% endif %}

trydjango/mysite/templates/home.html
{% extends 'base.html' %}
{% block content %}

<section id="hero" class="mb-5">
    {% include 'banners/banners_carousel.html' %}
</section>

<section id="featured" class="mb-5">
    {% include 'products/product_featured.html' %}
</section>

<section id="our-services" class="mb-5">
    {% include 'partials/services.html' %}
</section>

<section id="bestsellers" class="mb-5">
    {% include 'products/product_bestsellers.html' %}
</section>

<section id="video" class="mb-5">
    <div class="container text-center">
        {% for video in videos %}
        {% if video and video.code %}
        {% autoescape off %}
        {{ video.code }}
        {% endautoescape %}
        {% endif %}
        {% endfor %}
    </div>
</section>

<section id="most-viewed" class="mb-5">
    {% include 'products/product_most_viewed.html' %}
</section>

<section id="testimonials" class="mb-5">
    {% include 'partials/testimonials.html' %}
</section>

<section id="sitemap" class="mb-5">
    {% include 'partials/sitemap.html' %}
</section>

<footer id="footer" class="py-5 bg-dark text-white">
    <div class="container">
        <div class="card">
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <a href="#body" class="card-link">Back to Top</a>
                </blockquote>
            </div>
        </div>
    </div>
</footer>

{% endblock %}

trydjango/mysite/templates/navbar.html
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a href="/" class="nav-link">Home</a>
            </li>
            <li class="nav-item">
                <a href="/contact" class="nav-link">Contact</a>
            </li>
            <li class="nav-item">
                <a href="/about" class="nav-link">About</a>
            </li>
            <li class="nav-item">
                <a href="/products" class="nav-link">Products</a>
            </li>
           <!-- <li class="nav-item">
                <a href="/blog" class="nav-link">Blog</a>
            </li>-->
            <!--            <li class="nav-item">-->
            <!--                <a href="/admin" class="nav-link">Admin</a>-->
            <!--            </li>-->
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <button type="button" class="btn btn-light dropdown-toggle" id="navbarDropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                </button>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="/accounts/profile">Profile</a>
                    <a class="dropdown-item" href="/cart">My Cart</a>
<!--                    <a class="dropdown-item" href="#">My Orders</a>-->
<!--                    <a class="dropdown-item" href="#">Wish List</a>-->
                    <a class="dropdown-item" href="/accounts/logout">Logout</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <span class="nav-link"><a class="btn btn-light" href="/accounts/login">Login</a></span>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>

trydjango/mysite/templates/social.html
{% extends 'base.html' %}


{% block content %}
    <h1>Social Page</h1>

    <p>This is a template</p>
{% endblock %}